DROP TABLE IF EXISTS COUNTRYCODES CASCADE;

CREATE TABLE COUNTRYCODES (
  ID SERIAL PRIMARY KEY,
  COUNTRYCODE VARCHAR(255)
);

INSERT INTO COUNTRYCODES VALUES( DEFAULT, 'UK');
INSERT INTO COUNTRYCODES VALUES( DEFAULT, 'US');
INSERT INTO COUNTRYCODES VALUES( DEFAULT, 'NL');
