DROP TABLE IF EXISTS PRODUCT_ORDER CASCADE;
CREATE TABLE PRODUCT_ORDER ( ProductId VARCHAR(255), OrderId VARCHAR(255));
INSERT INTO PRODUCT_ORDER VALUES('ProductA','OrderA');
INSERT INTO PRODUCT_ORDER VALUES('ProductA','OrderB');
INSERT INTO PRODUCT_ORDER VALUES('ProductB','OrderA');
INSERT INTO PRODUCT_ORDER VALUES('ProductA','OrderA');
